import { Goal, Task, Beat, Playlist, DailyReview } from '../types';

export function getTodayDateString(): string {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function generateSampleData(userId: string): {
  goals: Goal[];
  tasks: Task[];
  beats: Beat[];
  playlists: Playlist[];
  reviews: DailyReview[];
} {
  const today = getTodayDateString();
  const now = Date.now();

  const beats: Beat[] = [
    {
      id: 'beat_midnight',
      userId,
      title: 'Midnight',
      audioUrl: '',
      duration: 184,
      bpm: 174,
      key: 'F# minor',
      genre: 'Drum & Bass',
      tags: ['dnb', 'atmospheric', 'roller', 'liquid'],
      status: 'finished',
      notes: 'Deep sub bass with crisp jungle breaks. Rhodes piano in the intro, heavy switch on the second drop.',
      color: '#6366f1',
      isFavorite: true,
      createdAt: now - 86400000 * 5,
      uploadedAt: now - 86400000 * 5,
    },
    {
      id: 'beat_after_hours',
      userId,
      title: 'After Hours',
      audioUrl: '',
      duration: 142,
      bpm: 140,
      key: 'D minor',
      genre: 'Dark Trap',
      tags: ['trap', 'dark', '808', 'aggressive'],
      status: 'wip',
      notes: '808 slide pattern needs slight saturation in the low-mids. Need to record live vocal chops.',
      color: '#f43f5e',
      isFavorite: true,
      createdAt: now - 86400000 * 2,
      uploadedAt: now - 86400000 * 2,
    },
    {
      id: 'beat_tokyo_rain',
      userId,
      title: 'Tokyo Rain',
      audioUrl: '',
      duration: 156,
      bpm: 85,
      key: 'C major',
      genre: 'Lo-Fi Chill',
      tags: ['lofi', 'chill', 'rain', 'study', 'relax'],
      status: 'finished',
      notes: 'Recorded real window rain ambience on Zoom H6. Electric piano running through tape cassette simulation.',
      color: '#f59e0b',
      isFavorite: false,
      createdAt: now - 86400000 * 10,
      uploadedAt: now - 86400000 * 10,
    },
    {
      id: 'beat_neon_drift',
      userId,
      title: 'Neon Drift',
      audioUrl: '',
      duration: 210,
      bpm: 128,
      key: 'A minor',
      genre: 'Synthwave',
      tags: ['synthwave', 'retro', 'analog', 'driving'],
      status: 'released',
      notes: 'Completed master version with 80s gated reverb snare, Prophet-6 arpeggios, and Moog bass.',
      color: '#06b6d4',
      isFavorite: true,
      createdAt: now - 86400000 * 20,
      uploadedAt: now - 86400000 * 20,
    },
    {
      id: 'beat_velvet_groove',
      userId,
      title: 'Velvet Groove',
      audioUrl: '',
      duration: 165,
      bpm: 92,
      key: 'G minor',
      genre: 'Boom Bap',
      tags: ['boombap', '90s', 'vinyl', 'classic'],
      status: 'wip',
      notes: 'Chopped jazz guitar sample with unquantized MPC swing. Adding live bass guitar next session.',
      color: '#10b981',
      isFavorite: false,
      createdAt: now - 86400000 * 1,
      uploadedAt: now - 86400000 * 1,
    },
  ];

  const goals: Goal[] = [
    {
      id: 'goal_music_ep',
      userId,
      title: 'Finish & Mix "Midnight" Beat for EP',
      description: 'Complete the final drum arrangement, automate filters, and polish the master limiter.',
      date: today,
      priority: 'high',
      status: 'active',
      createdAt: now - 86400000,
      updatedAt: now - 86400000,
    },
    {
      id: 'goal_dev_skills',
      userId,
      title: 'Advance Architecture & Core Programming',
      description: 'Review systems design, data structures, and build responsive modular UI.',
      date: today,
      priority: 'high',
      status: 'active',
      createdAt: now - 86400000 * 2,
      updatedAt: now - 86400000 * 2,
    },
    {
      id: 'goal_health',
      userId,
      title: 'Physical Conditioning & Mind Cleanse',
      description: 'Complete morning routine, stay hydrated, and maintain focus blocks.',
      date: today,
      priority: 'medium',
      status: 'active',
      createdAt: now - 86400000 * 3,
      updatedAt: now - 86400000 * 3,
    },
  ];

  const tasks: Task[] = [
    {
      id: 'task_1',
      userId,
      goalId: 'goal_health',
      title: 'Morning Workout & Mobility',
      description: 'Warmup stretches, 5km tempo run, and kettlebell circuit.',
      date: today,
      channelId: 'chan_life',
      startTime: '07:30',
      endTime: '08:45',
      durationMinutes: 75,
      priority: 'medium',
      status: 'completed',
      subtasks: [
        { id: 'sub_1', title: '5km tempo run', done: true },
        { id: 'sub_2', title: 'Kettlebell swings & mobility', done: true },
      ],
      order: 1,
      completedAt: now - 3600000 * 4,
      actualDurationMinutes: 75,
      createdAt: now - 86400000,
      updatedAt: now - 3600000 * 4,
    },
    {
      id: 'task_2',
      userId,
      goalId: 'goal_dev_skills',
      channelId: 'chan_code',
      title: 'Full-Stack Architecture & API Design',
      description: 'Design data models, optimize queries, and implement state caches.',
      date: today,
      startTime: '09:15',
      endTime: '11:30',
      durationMinutes: 135,
      priority: 'high',
      status: 'completed',
      subtasks: [
        { id: 'sub_3', title: 'Review Firestore security rules', done: true },
        { id: 'sub_4', title: 'Test realtime task listeners', done: true },
        { id: 'sub_5', title: 'Benchmark timeline rendering', done: false },
      ],
      order: 2,
      completedAt: now - 3600000 * 1,
      actualDurationMinutes: 135,
      createdAt: now - 86400000,
      updatedAt: now - 3600000 * 1,
    },
    {
      id: 'task_3',
      userId,
      goalId: 'goal_music_ep',
      channelId: 'chan_beat',
      title: 'Music Production — Finish Drum Arrangement',
      description: 'Fine-tune hi-hat rolls, layer snare transient, and automate master filter drop.',
      date: today,
      startTime: '13:30',
      endTime: '15:15',
      durationMinutes: 105,
      priority: 'critical',
      status: 'in_progress',
      associatedBeatId: 'beat_midnight',
      notes: 'Make sure the second drop has the reese bass sub pitch envelope.',
      notesCount: 2,
      subtasks: [
        { id: 'sub_6', title: 'Hi-hat velocity curves', done: true },
        { id: 'sub_7', title: 'Layer snare transients', done: false },
        { id: 'sub_8', title: 'Automate master high-pass filter', done: false },
      ],
      order: 3,
      createdAt: now - 86400000,
      updatedAt: now,
    },
    {
      id: 'task_4',
      userId,
      goalId: 'goal_music_ep',
      channelId: 'chan_beat',
      title: 'Sound Design — 808 Glides & Vocal Textures',
      description: 'Work on After Hours project stems and bounce new audio samples.',
      date: today,
      startTime: '15:45',
      endTime: '17:15',
      durationMinutes: 90,
      priority: 'high',
      status: 'planned',
      associatedBeatId: 'beat_after_hours',
      order: 4,
      createdAt: now - 86400000,
      updatedAt: now,
    },
    {
      id: 'task_5',
      userId,
      goalId: 'goal_dev_skills',
      channelId: 'chan_research',
      title: 'Mathematics & Algorithm Practice',
      description: 'Solve graph traversal and dynamic programming practice questions.',
      date: today,
      startTime: '17:45',
      endTime: '19:00',
      durationMinutes: 75,
      priority: 'medium',
      status: 'planned',
      order: 5,
      createdAt: now - 86400000,
      updatedAt: now,
    },
    {
      id: 'task_6',
      userId,
      channelId: 'chan_life',
      title: 'Daily Review & Studio Session Wrap-up',
      description: 'Log accomplishments, review missed time blocks, and prep tomorrow.',
      date: today,
      startTime: '21:00',
      endTime: '21:30',
      durationMinutes: 30,
      priority: 'low',
      status: 'planned',
      order: 6,
      createdAt: now - 86400000,
      updatedAt: now,
    },
  ];

  const playlists: Playlist[] = [
    {
      id: 'pl_best_beats',
      userId,
      name: 'Best Beats',
      description: 'Top finished master productions ready for release or placements.',
      beatIds: ['beat_midnight', 'beat_neon_drift', 'beat_tokyo_rain'],
      createdAt: now - 86400000 * 4,
    },
    {
      id: 'pl_wips',
      userId,
      name: 'WIP Studio Vault',
      description: 'Work-in-progress drafts and loop ideas.',
      beatIds: ['beat_after_hours', 'beat_velvet_groove'],
      createdAt: now - 86400000 * 2,
    },
    {
      id: 'pl_focus',
      userId,
      name: 'Focus & Flow',
      description: 'Atmospheric and chill beats for coding & deep study sessions.',
      beatIds: ['beat_tokyo_rain', 'beat_neon_drift', 'beat_midnight'],
      createdAt: now - 86400000 * 1,
    },
  ];

  const reviews: DailyReview[] = [
    {
      id: 'rev_yesterday',
      userId,
      date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
      goalsCompleted: 2,
      totalGoals: 3,
      tasksCompleted: 5,
      tasksMissed: 1,
      tasksRescheduled: 1,
      totalPlannedMinutes: 360,
      totalCompletedMinutes: 315,
      completionRate: 88,
      whatWentWell: 'Cruised through morning workouts and locked in 2 uninterrupted hours on the synthwave master.',
      whatToImprove: 'Give 15 minutes buffer between coding and music studio sessions to prevent mental fatigue.',
      moodRating: 5,
      createdAt: now - 86400000,
    },
  ];

  return { goals, tasks, beats, playlists, reviews };
}
